[DEV-874] removed enabled flag
kirasystems/compojure-throttle pull request #2
Opened 2018-09-18 19:33 UTC by Elknar

As per @gclapperton 's request, removed the enabled flag. 

Throttler is now enabled/disabled based on the existence of the lax subnet env var.

2018-09-18 19:35 UTC, MatthewDarling approved these changes

2018-09-18 19:45 UTC, prefuzek requested changes
A couple very minor changes, otherwise looks good!

2018-09-18 19:45 UTC, prefuzek commented on test/compojure_throttle/core_test.clj
> +  (:require [clj.ip :as ip]
This namespace is unused.

2018-09-18 19:45 UTC, prefuzek commented on src/compojure_throttle/core.clj
> +(defn ip-lax-subnet
Shouldn't this still be private?

2018-09-18 19:55 UTC, MatthewDarling approved these changes

2018-09-19 17:34 UTC, prefuzek approved these changes

2018-09-19 17:41 UTC, merged